### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by kassak** [swdotcom/swdc-intellij-music-time#23]
**Describe the bug**
Saw your plugin in user freeze reports
```paste below
	at com.musictime.intellij.plugin.fs.FileManager.getNumericItem(FileManager.java:390)
	at com.musictime.intellij.plugin.managers.SessionDataManager.getTimeBetweenLastPayload(SessionDataManager.java:82)
	at com.musictime.intellij.plugin.KeystrokeCount.processKeystrokes(KeystrokeCount.java:260)
	at com.musictime.intellij.plugin.SoftwareCoEventManager.lambda$checkFocusState$1(SoftwareCoEventManager.java:59)
	at com.musictime.intellij.plugin.SoftwareCoEventManager$$Lambda$2982/0x0000000801a90440.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$359/0x000000080029c440.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop@11.0.8/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.8/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.8/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.8/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.8/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.8/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.8/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.ide.IdeEventQueue$$Lambda$676/0x000000080089f840.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.ide.IdeEventQueue$$Lambda$673/0x0000000800899c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.8/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
**ISSUE TYPE**
- Bug Report

**Comment by maxence-lefebvre** [comment]
Same here, I had to disable your plugin after your last update.

**Comment by creplogle** [comment]
Same here. I also noticed that there isn't any information provided for this update... I guess that "What's new" is that the plugin is buggy.

**Comment by xavluiz** [comment]
Thank you for the issue update and we apologize for the late response. We'll look into this right away.
Regards.

**Comment by xavluiz** [comment]
We will be publishing v2.0.9 with a fix for this call and other optimizations. This should be available in the marketplace in a few days.
thank you.

**Comment by xavluiz** [comment]
Let us know if there are any other issues. v2.0.10 is also now available with a performance fix. Thanks.

**Comment by Ignaciocl** [comment]
There is still a minor freeze (from 5s to 10s)  when using the IDE for me, after that minifreeze the plugin works as expected and no error is thrown, but that minifreeze is kind of annoying as it makes me stop working to wait it to recharge my account.
I don't know if this is expected or not, I can reproduce this in linux and at mac, both with intellij ultimate edition and Clion at the last version of both, do I need to activate something more at spotify?
