### ISSUE TITLE
NoClassDefFoundError: okhttp3/OkHttpClient

### ISSUE THREAD

**Issue by Spurlos** [swdotcom/swdc-intellij-music-time#25]
**Describe the bug**
```paste below
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
	at com.swdc.snowplow.tracker.manager.TrackerManager.<init>(TrackerManager.java:47)
	at com.musictime.intellij.plugin.managers.EventTrackerManager.init(EventTrackerManager.java:47)
	at com.musictime.intellij.plugin.SoftwareCoMusic.initializeUserInfo(SoftwareCoMusic.java:183)
	at com.musictime.intellij.plugin.SoftwareCoMusic.initializeUserInfoWhenProjectsReady(SoftwareCoMusic.java:170)
	at com.musictime.intellij.plugin.SoftwareCoMusic.access$000(SoftwareCoMusic.java:30)
	at com.musictime.intellij.plugin.SoftwareCoMusic$1.run(SoftwareCoMusic.java:165)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient PluginClassLoader[PluginDescriptor(name=Music Time, id=com.musictime.intellij.plugin, path=/home/spurlos/.local/share/JetBrains/PhpStorm2020.2/musictime, version=2.0.11)] com.intellij.ide.plugins.cl.PluginClassLoader@465479a
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 8 more
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Just launch IDE

**Expected behavior**
```paste below
No error popup and stable plugin work
```

**ACTUAL RESULTS**

```paste below
IDE becomes unstable if MusicTime is being used
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Plugin version 2.0.11

**Additional context**
```paste below

```

**Comment by mmclead** [comment]
Thank you @Spurlos for the report.   We'll look at it right away.
